### ISSUE TITLE
Duplicate type error!

### ISSUE THREAD

**Issue by OdSazib** [PixelExperience-Devices/device_xiaomi_sdm845-common#3]
https://github.com/PixelExperience-Devices/device_xiaomi_sdm845-common/blob/3b2dba9e2c602f3c2b2acecd81dfa40fab709c7d/sepolicy/vendor/file.te#L10

Hi does this work for you? for me, I face the following consequences:

https://del.dog/yttofivock

this is the error (already defined in rom): qcom/sepolicy/generic/vendor/common/file.te
 but when I delete these duplicate type from device tree, it shows this error:
https://del.dog/imegukiham

So system_stat should work even without those policies in the device tree
but there is a denial spamming in log

7-16 21:20:37.163 W/power@1.3-servi(819): type=1400 audit(0.0:141): avc: denied { read } for name="system_stats" dev="debugfs" ino=13065 scontext=u:r:hal_power_default:s0 tcontext=u:object_r:debugfs:s0 tclass=file permissive=0

This^ is a  neverallow

I hope you got it working, it would be appreciated if you tell me

**Comment by jjpprrrr** [comment]
Are you sure the duplicate type is caused by debugfs_rpm not debugfs_wlan?

```
device/xiaomi/sdm660-common/sepolicy/vendor/file.te:3:ERROR 'Duplicate declaration of type' at token ';' on line 89241:
type debugfs_rpm, debugfs_type, fs_type;
type debugfs_wlan, debugfs_type, fs_type;
```

**Comment by OdSazib** [comment]
Yes, I already give u error message

I tried deleting debugfs_wlan and still the error is generated for debugfs_rpm

**Comment by OdSazib** [comment]
Yes you are right, thank you.

good news is it was not working a month ago even by removing debugfs_wlan.
Now it works :D
